//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekres.Notes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekres.Notes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page left.
        /// </summary>
        internal static string Add_new_page_left {
            get {
                return ResourceManager.GetString("Add new page left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new page right.
        /// </summary>
        internal static string Add_new_page_right {
            get {
                return ResourceManager.GetString("Add new page right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a brand new book.
        /// </summary>
        internal static string Create_a_brand_new_book {
            get {
                return ResourceManager.GetString("Create a brand new book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy book.
        /// </summary>
        internal static string Destroy_Book {
            get {
                return ResourceManager.GetString("Destroy Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book title.
        /// </summary>
        internal static string Edit_book_title {
            get {
                return ResourceManager.GetString("Edit book title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit page title.
        /// </summary>
        internal static string Edit_page_title {
            get {
                return ResourceManager.GetString("Edit page title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Book.
        /// </summary>
        internal static string Empty_Book {
            get {
                return ResourceManager.GetString("Empty Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Page.
        /// </summary>
        internal static string Empty_Page {
            get {
                return ResourceManager.GetString("Empty Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the book&apos;s name below to confirm before destroying..
        /// </summary>
        internal static string Enter_the_book_s_title_below_to_confirm_before_destroying_ {
            get {
                return ResourceManager.GetString("Enter the book\'s title below to confirm before destroying.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book.
        /// </summary>
        internal static string New_Book {
            get {
                return ResourceManager.GetString("New Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current page.
        /// </summary>
        internal static string Remove_current_page {
            get {
                return ResourceManager.GetString("Remove current page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something....
        /// </summary>
        internal static string Write_something___ {
            get {
                return ResourceManager.GetString("Write something...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to permanently destroy {0}..
        /// </summary>
        internal static string You_are_about_to_permanently_destroy__0__ {
            get {
                return ResourceManager.GetString("You are about to permanently destroy {0}.", resourceCulture);
            }
        }
    }
}
