//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekres.Screenshot_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekres.Screenshot_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate image name was specified!.
        /// </summary>
        internal static string A_duplicate_image_name_was_specified_ {
            get {
                return ResourceManager.GetString("A duplicate image name was specified!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Zoom.
        /// </summary>
        internal static string Click_To_Zoom {
            get {
                return ResourceManager.GetString("Click To Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image?.
        /// </summary>
        internal static string Delete_Image_ {
            get {
                return ResourceManager.GetString("Delete Image?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Screenshot Notification.
        /// </summary>
        internal static string Disable_Screenshot_Notification {
            get {
                return ResourceManager.GetString("Disable Screenshot Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete image {0}..
        /// </summary>
        internal static string Failed_to_delete_image__0__ {
            get {
                return ResourceManager.GetString("Failed to delete image {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image name cannot be empty..
        /// </summary>
        internal static string Image_name_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Image name cannot be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different image name..
        /// </summary>
        internal static string Please_enter_a_different_image_name_ {
            get {
                return ResourceManager.GetString("Please enter a different image name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Image.
        /// </summary>
        internal static string Rename_Image {
            get {
                return ResourceManager.GetString("Rename Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Created!.
        /// </summary>
        internal static string Screenshot_Created_ {
            get {
                return ResourceManager.GetString("Screenshot Created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stereoscopic.
        /// </summary>
        internal static string Stereoscopic {
            get {
                return ResourceManager.GetString("Stereoscopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a normal screenshot..
        /// </summary>
        internal static string Take_a_normal_screenshot_ {
            get {
                return ResourceManager.GetString("Take a normal screenshot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a stereoscopic screenshot..
        /// </summary>
        internal static string Take_a_stereoscopic_screenshot_ {
            get {
                return ResourceManager.GetString("Take a stereoscopic screenshot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters are not allowed: {0}.
        /// </summary>
        internal static string The_following_characters_are_not_allowed___0_ {
            get {
                return ResourceManager.GetString("The following characters are not allowed: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image doesn&apos;t exist anymore!.
        /// </summary>
        internal static string The_image_file_doesn_t_exist_anymore_ {
            get {
                return ResourceManager.GetString("The image file doesn\'t exist anymore!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is in use by another process..
        /// </summary>
        internal static string The_image_file_is_in_use_by_another_process_ {
            get {
                return ResourceManager.GetString("The image file is in use by another process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image name contains invalid characters..
        /// </summary>
        internal static string The_image_name_contains_invalid_characters_ {
            get {
                return ResourceManager.GetString("The image name contains invalid characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename image {0}..
        /// </summary>
        internal static string Unable_to_rename_image__0__ {
            get {
                return ResourceManager.GetString("Unable to rename image {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavourite.
        /// </summary>
        internal static string Unfavourite {
            get {
                return ResourceManager.GetString("Unfavourite", resourceCulture);
            }
        }
    }
}
